package Exception;

import javax.swing.JOptionPane;
/*
 * USAGE:
 * try {
 * 		throw new ErrorControl(message_to_show, Info/Warning/Error);
 * } catch (ErrorControl e) {
 * 		e.printStackTrace();
 * }
 * 
 */
public class ErrorControl extends Exception {
    // Error UID (Generated by Eclipse)
	private static final long serialVersionUID = 1L;

	public ErrorControl(String errorMessage, String type) {
        super(errorMessage, null);
        switch (type) {
        	case "Info":
        		JOptionPane.showMessageDialog(null, errorMessage, "Info: ", JOptionPane.INFORMATION_MESSAGE);
        		break;
        	case "Warning":
        		JOptionPane.showMessageDialog(null, errorMessage, "Warning: ", JOptionPane.WARNING_MESSAGE);
        		break;
        	case "Error":
        		JOptionPane.showMessageDialog(null, errorMessage, "Error: ", JOptionPane.ERROR_MESSAGE);
        		break;
        	default:
        		JOptionPane.showMessageDialog(null, errorMessage, "Info: ", JOptionPane.INFORMATION_MESSAGE);
        		break;
        } 
    }
	
	@Override
	public String toString() {
		return null;
	}
}